global:
    # How frequently to scrape targets by default.
    scrape_interval: 1m
    # How long until a scrape request times out.
    scrape_timeout: 10s
    # How frequently to evaluate rules.
    evaluation_interval: 1m

rule_files:
    - "/etc/prometheus/alert.rules"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
    - job_name: "frontend"
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: '/metrics'
      static_configs:
        - targets: ['front-end:8079']

    - job_name: "catalogue"
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: '/metrics'
      static_configs:
        - targets: ['catalogue:8081']

    - job_name: "payment"
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: '/metrics'
      static_configs:
        - targets: ['payment:8080']

    - job_name: "user"
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: '/metrics'
      static_configs:
        - targets: ['user:8084']

    - job_name: "orders"
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: '/metrics'
      static_configs:
        - targets: ['orders:80']

    - job_name: "cart"
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: '/metrics'
      static_configs:
        - targets: ['carts:80']

    - job_name: "shipping"
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: '/metrics'
      static_configs:
        - targets: ['shipping:80']

    - job_name: "queue-master"
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: '/prometheus'
      static_configs:
        - targets: ['queue-master:80']

    - job_name: 'node-exporter'
      scrape_interval: 5s
      metrics_path: 'metrics'
      static_configs:
        - targets: ['nodeexporter:9100']
    - job_name: 'cadvisor'
      scrape_interval: 5s
      metrics_path: '/metrics'
      static_configs:
        - targets: ['cadvisor:8080']
    - job_name: 'tempo'
      scrape_interval: 5s
      metrics_path: '/metrics'
      static_configs:
        - targets: ['tempo:3200']