server:
  http_listen_port: 3200
  grpc_listen_port: 3201
  log_level: warn

multitenancy_enabled: false
auth_enabled: false

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    zipkin:
      endpoint: 0.0.0.0:9411

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  processor:
    service_graphs:
      dimensions:
        - service.namespace
        - service.version
      enable_client_server_prefix: true
    span_metrics:
      dimensions:
        - service.namespace

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal

querier:
  {}

query_frontend:
  {}

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
      collection_interval: 5s
