server:
  http_listen_port: 3200
  grpc_listen_port: 3201
  log_level: info

multitenancy_enabled: false
auth_enabled: false

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    zipkin:
      endpoint: 0.0.0.0:9411

ingester:
  lifecycler:
    ring:
      replication_factor: 1
  trace_idle_period: 10s
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
    wal:
      path: /tmp/tempo/wal

querier:
  {}

query_frontend:
  {}
