#!/bin/bash
# Quick commands for working with OpenTelemetry tracing

echo "OpenTelemetry Tracing - Quick Reference"
echo "========================================"
echo ""
echo "📊 View Traces:"
echo "  Grafana:  http://localhost:3000 (admin/foobar)"
echo "            Navigate: Explore → Tempo"
echo ""
echo "🔍 Check Trace Count:"
echo "  curl 'http://localhost:3200/api/search?limit=100' 2>/dev/null | grep traceID | wc -l"
echo ""
echo "📈 View Service Graph:"
echo "  Grafana:  http://localhost:3000"
echo "            Navigate: Explore → Prometheus"
echo "            Query: traces_service_graph_request_total"
echo ""
echo "🚦 Generate Traffic:"
echo "  for i in {1..50}; do curl -s http://localhost:80/ >/dev/null; done"
echo ""
echo "✅ Verify Tracing:"
echo "  ./verify-tracing.sh"
echo ""
echo "📚 Documentation:"
echo "  TRACING-SUMMARY.md      - Implementation summary"
echo "  TRACING-README.md       - Complete guide"
echo "  OBSERVABILITY-EXPLAINED.md - Full observability stack"
echo ""
echo "🎯 Services with Tracing:"
echo "  ✅ carts"
echo "  ✅ orders"
echo "  ✅ shipping"
echo "  ✅ queue-master"
echo ""
echo "  ⚠️  catalogue (Go - needs rebuild)"
echo "  ⚠️  payment (Go - needs rebuild)"
echo "  ⚠️  user (Go - needs rebuild)"
echo "  ⚠️  front-end (Node.js - incompatible runtime)"
echo ""
